export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ProtectedRoutePage } from './ProtectedRoutePage'
export { ProductPage } from './ProductPage'
