export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ProductPage } from './ProductPage'
export { CartPage } from './CartPage'
export { HistoryPage } from './HistoryPage'
export { SearchPage } from './SearchPage'
